export const INCREMENTBY1 = "INCREMENTBY1";
export const INCREMENTBY10 = "INCREMENTBY10";
export const DECREMENTBY1 = "DECREMENTBY1";
export const DECREMENTBY10 = "DECREMENTBY10";
export const STORE_RESULT = "STORE_RESULT";
export const DELETE_RESULT = "DELETE_RESULT";